class ContractError(ValueError):
    code: str
    operation: str
    message: str
    scope: dict[str, str]

__version__: str
def validate_run_config_json(input: str) -> str: ...
def capabilities_json() -> str: ...
def parse_decimal(input: str) -> str: ...
def parse_price(input: str) -> str: ...
def round_decimal(input: str, scale: int) -> str: ...
def divide_decimal(numerator: str, denominator: str, scale: int) -> str: ...
def legal_quantity(quantity: int, numerator: str, denominator: str, step: int) -> int: ...
def roundtrip_ns(input: str) -> str: ...
def validate_market_event_json(input: str) -> str: ...
def validate_commission_config_json(input: str, overrides: str = "{}") -> str: ...
def compose_official_fee_config_json(input: str) -> str: ...
def indicator_json(input: str) -> str: ...
MAX_VIEW_ROWS: int
MAX_VIEW_BYTES: int

class ReadView:
    def __init__(self, boundary: str, max_rows: int = 10000, max_bytes: int = 67108864) -> None: ...
    def check(self) -> None: ...
    def visible_key_json(self, key: str) -> bool: ...
    def reset(self) -> None: ...
    def resources_json(self) -> str: ...
    def expire(self) -> None: ...
    def push_market(self, metadata: str, payload: bytes) -> None: ...
    def push_research(self, metadata: str, payload: bytes) -> None: ...
    def prices_json(self, request: str, source_frequency: str, calendar: str = '[]') -> str: ...
    def research_json(self, request: str) -> str: ...
    def research_prices(self, request: str) -> None: ...
    def current_json(self, securities: str) -> str: ...
