class ContractError(ValueError):
    code: str
    operation: str
    message: str
    scope: dict[str, str]

__version__: str
def validate_run_config_json(input: str) -> str: ...
def capabilities_json() -> str: ...
def parse_decimal(input: str) -> str: ...
def parse_price(input: str) -> str: ...
def round_decimal(input: str, scale: int) -> str: ...
def divide_decimal(numerator: str, denominator: str, scale: int) -> str: ...
def legal_quantity(quantity: int, numerator: str, denominator: str, step: int) -> int: ...
def roundtrip_ns(input: str) -> str: ...
def validate_market_event_json(input: str) -> str: ...
def validate_commission_config_json(input: str, overrides: str = "{}") -> str: ...
def compose_official_fee_config_json(input: str) -> str: ...
