from decimal import Decimal
from typing import Mapping, Sequence
from pandas import DataFrame
Values = Sequence[float | Decimal | int | None]
def sma(values: Values, period: int) -> DataFrame: ...
def ema(values: Values, period: int) -> DataFrame: ...
def rsi(values: Values, period: int = 14) -> DataFrame: ...
def atr(high: Values, low: Values, close: Values, period: int = 14) -> DataFrame: ...
def macd(values: Values, fast: int = 12, slow: int = 26, signal: int = 9) -> DataFrame: ...
def rolling_std(values: Values, period: int, ddof: int = 1) -> DataFrame: ...
def rank(values: Mapping[str, float | Decimal | int | None], ascending: bool = True) -> DataFrame: ...
SMA = sma
EMA = ema
RSI = rsi
ATR = atr
MACD = macd
