[workspace]
members = ["crates/qf-core", "crates/qf-python"]
resolver = "3"

[workspace.package]
version = "0.3.0"
edition = "2024"
rust-version = "1.90"
license = "Apache-2.0"

[workspace.dependencies]
qf-core = { path = "crates/qf-core" }
rust_decimal = { version = "=1.43.0", default-features = false, features = ["std"] }
bnum = { version = "=0.14.4", default-features = false }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = { version = "=1.0.151", features = ["arbitrary_precision"] }
pyo3 = "=0.29.2"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
