import { useEffect, useRef, useState, type ReactNode } from "react";
import { X, Search } from "lucide-react";
import { fetchRunWorkbench, type WorkbenchPage } from "../../api/backtestRuns";
import { listStrategyRevisions, type StrategyRevisionSummary } from "../../api/strategies";
import { listComparisons, type SavedComparison, type SavedComparisonPage } from "../../api/backtestComparisons";
import { isDialogBackdropClick } from "../../components/controls/dialogBackdrop";
export function ComparisonDrawer({ title, onClose, children, narrow = false, centered = false }: { title: string; onClose: () => void; children: ReactNode; narrow?: boolean; centered?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const prior = document.activeElement as HTMLElement, overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; ref.current?.showModal(); return () => { document.body.style.overflow = overflow; if (prior?.isConnected) prior.focus(); }; }, []);
  return <dialog ref={ref} aria-label={title} className={`qcmp-drawer ${centered ? "qcmp-confirm" : `qf-create-drawer ${narrow ? "" : "qf-create-wide"}`}`} onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (isDialogBackdropClick(e)) onClose(); }}><header><div><small>BACKTEST COMPARISON</small><h2>{title}</h2></div><button aria-label={`关闭${title}`} onClick={onClose}><X size={18}/></button></header>{children}</dialog>;
}
export function AddRunsDrawer({ selected, onToggle, onClose }: { selected: string[]; onToggle: (id: string) => void; onClose: () => void }) {
  const [search, setSearch] = useState(""), [query, setQuery] = useState({ search: "", offset: 0 }), [page, setPage] = useState<WorkbenchPage | null>(null), [loading, setLoading] = useState(false), [error, setError] = useState(""), [retry, setRetry] = useState(0);
  const [revisions, setRevisions] = useState<Record<string, StrategyRevisionSummary>>({});
  useEffect(() => { const timer = setTimeout(() => setQuery(q => q.search === search.trim() ? q : { search: search.trim(), offset: 0 }), 300); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { const c = new AbortController(); setLoading(true); setError(""); fetchRunWorkbench({ ...query, status: "succeeded" }, c.signal).then(async value => { if (c.signal.aborted) return; setPage(value); const strategies = [...new Set(value.items.map(r => r.strategy_id).filter((id): id is string => !!id))]; const found = await Promise.allSettled(strategies.map(id => listStrategyRevisions(id))); if (!c.signal.aborted) setRevisions(previous => ({ ...previous, ...Object.fromEntries(found.flatMap(result => result.status === "fulfilled" ? result.value.map(r => [r.id, r]) : [])) })); }).catch(e => { if (!c.signal.aborted) setError(e.message); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [query, retry]);
  return <ComparisonDrawer title="添加运行" onClose={onClose}><div className="qcmp-drawer-body"><label className="qcmp-search"><Search size={16}/><input autoFocus aria-label="搜索已完成运行" placeholder="搜索策略名称或运行 ID" value={search} onChange={e => setSearch(e.target.value)} maxLength={200}/></label><p className="qcmp-note">已选择 {selected.length} / 10 个运行；勾选立即加入当前对比。</p><div className="qcmp-loading" role="status">{loading ? "正在读取运行…" : ""}</div>{error && <p role="alert" className="qcmp-error">{error}<button onClick={() => setRetry(v => v + 1)}>重试</button></p>}
    {page?.items.map(run => <label className="qcmp-picker-row" key={run.run_id}><input type="checkbox" aria-label={`选择运行 ${run.run_id}`} checked={selected.includes(run.run_id)} disabled={loading || !selected.includes(run.run_id) && selected.length >= 10} onChange={() => onToggle(run.run_id)}/><span><strong>{run.strategy_name || "策略名称未记录"} · v{run.revision_number || "—"}</strong><span>{run.strategy_revision_id && revisions[run.strategy_revision_id] ? revisions[run.strategy_revision_id].alias || "未命名版本" : "版本别名暂不可用"}</span><code>{run.run_id}</code></span></label>)}{page && !page.items.length && <p className="qcmp-empty">没有可选的已完成运行。</p>}
    </div><footer><span>{page ? `共 ${page.total} 个运行` : "—"}</span><button disabled={loading || query.offset === 0} onClick={() => setQuery(q => ({ ...q, offset: Math.max(0, q.offset - 20) }))}>上一页</button><button disabled={loading || !page?.has_more} onClick={() => setQuery(q => ({ ...q, offset: q.offset + 20 }))}>下一页</button><button className="qcmp-primary" onClick={onClose}>完成选择</button></footer></ComparisonDrawer>;
}
export function SavedListDrawer({ onOpen, onRename, onDelete, onClose }: { onOpen: (item: SavedComparison) => void; onRename: (item: SavedComparison) => void; onDelete: (item: SavedComparison) => void; onClose: () => void }) {
  const [page, setPage] = useState<SavedComparisonPage | null>(null), [offset, setOffset] = useState(0), [loading, setLoading] = useState(false), [error, setError] = useState(""), [retry, setRetry] = useState(0);
  useEffect(() => { const c = new AbortController(); setLoading(true); setError(""); listComparisons(offset, c.signal).then(value => { if (!c.signal.aborted) setPage(value); }).catch(e => { if (!c.signal.aborted) setError(e.message); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [offset, retry]);
  return <ComparisonDrawer title="已保存的对比" onClose={onClose}><div className="qcmp-drawer-body"><div className="qcmp-loading" role="status">{loading ? "正在读取保存列表…" : ""}</div>{error && <p role="alert" className="qcmp-error">{error}<button onClick={() => setRetry(n => n + 1)}>重试</button></p>}{page?.items.map(item => <article className="qcmp-saved-row" key={item.id}><div><strong>{item.name}</strong><small>{item.run_ids.length} 个运行 · 更新于 {new Date(item.updated_at).toLocaleString("zh-CN")}</small></div><div className="qcmp-actions"><button disabled={loading} onClick={() => onOpen(item)}>打开</button><button disabled={loading} onClick={() => onRename(item)}>重命名</button><button disabled={loading} onClick={() => onDelete(item)}>删除</button></div></article>)}{page && !page.items.length && <p className="qcmp-empty">尚无保存的对比。</p>}</div><footer><span>{page ? `共 ${page.total} 项` : "—"}</span><button disabled={loading || offset === 0} onClick={() => setOffset(v => Math.max(0, v - 20))}>上一页</button><button disabled={loading || !page?.has_more} onClick={() => setOffset(v => v + 20)}>下一页</button></footer></ComparisonDrawer>;
}
export function NameDrawer({ initialName, title, onSubmit, onClose }: { initialName: string; title: string; onSubmit: (name: string) => Promise<void>; onClose: () => void }) {
  const [name, setName] = useState(initialName), [busy, setBusy] = useState(false), [error, setError] = useState(""), [discard, setDiscard] = useState(false); const working = useRef(false);
  const close = () => { if (working.current) return; if (name !== initialName) setDiscard(true); else onClose(); };
  useEffect(() => { if (name === initialName) return; const prevent = (e: BeforeUnloadEvent) => e.preventDefault(); window.addEventListener("beforeunload", prevent); return () => window.removeEventListener("beforeunload", prevent); }, [name, initialName]);
  return <ComparisonDrawer title={title} onClose={close} narrow>{discard ? <div className="qcmp-drawer-body"><h3>放弃未保存的名称？</h3><div className="qcmp-actions"><button autoFocus onClick={() => setDiscard(false)}>继续编辑</button><button onClick={onClose}>放弃并关闭</button></div></div> : <form onSubmit={async e => { e.preventDefault(); if (working.current || !name.trim()) return; working.current = true; setBusy(true); setError(""); try { await onSubmit(name.trim()); } catch (error) { setError(error instanceof Error ? error.message : "保存失败，请重试。"); } finally { working.current = false; setBusy(false); } }}><div className="qcmp-drawer-body"><label>对比名称<input autoFocus required maxLength={100} value={name} disabled={busy} onChange={e => setName(e.target.value)}/></label><p className="qcmp-note">保存运行列表、顺序和比较基准；再次打开时读取真实结果。</p>{error && <p role="alert" className="qcmp-error">{error}</p>}</div><footer><button type="button" disabled={busy} onClick={close}>取消</button><button className="qcmp-primary" disabled={busy || !name.trim()}>{busy ? "保存中…" : "保存"}</button></footer></form>}</ComparisonDrawer>;
}
