"""Add ETF corporate action source, normalized and coverage facts."""
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa
revision="20260830_02"; down_revision="20260830_01"; branch_labels=None; depends_on=None
def upgrade():
    uuid=sa.Uuid()
    op.create_table("corporate_action_source_facts", sa.Column("id",uuid,primary_key=True), sa.Column("source",sa.String(32),nullable=False), sa.Column("endpoint",sa.String(64),nullable=False), sa.Column("query_kind",sa.String(32)), sa.Column("query_value",sa.String(32)), sa.Column("ts_code",sa.String(32),nullable=False), sa.Column("ann_date",sa.Date()), sa.Column("payload",sa.JSON(),nullable=False), sa.Column("source_hash",sa.String(128),nullable=False), sa.Column("observed_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.UniqueConstraint("source","endpoint","query_kind","query_value","source_hash",name="uq_corp_source_snapshot"))
    op.create_index("ix_corp_source_code_ann","corporate_action_source_facts",["source","ts_code","ann_date"])
    op.create_table("corporate_action_facts", sa.Column("event_id",uuid,primary_key=True), sa.Column("logical_fact_key",sa.String(256),nullable=False), sa.Column("fact_version",sa.Integer(),nullable=False), sa.Column("supersedes_fact_id",uuid), sa.Column("instrument_id",uuid,nullable=False), sa.Column("action_type",sa.String(32),nullable=False), sa.Column("record_date",sa.Date()), sa.Column("ex_date",sa.Date()), sa.Column("source_payment_date",sa.Date()), sa.Column("source_arrival_date",sa.Date()), sa.Column("cash_effective_date",sa.Date()), sa.Column("cash_effective_phase",sa.String(32)), sa.Column("cash_amount_per_unit",sa.Numeric(24,12)), sa.Column("currency",sa.String(16)), sa.Column("entitlement_rule",sa.String(64)), sa.Column("cash_date_rule",sa.String(64)), sa.Column("timing_rule",sa.String(64)), sa.Column("source",sa.String(32),nullable=False), sa.Column("evidence",sa.JSON()), sa.Column("quality",sa.String(32)), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_index("ix_corp_facts_instrument_date","corporate_action_facts",["instrument_id","cash_effective_date"])
    op.create_unique_constraint("uq_corp_fact_version", "corporate_action_facts", ["logical_fact_key", "fact_version"])
    op.create_table("corporate_action_coverage_facts", sa.Column("id",uuid,primary_key=True), sa.Column("instrument_id",uuid,nullable=False), sa.Column("start_date",sa.Date(),nullable=False), sa.Column("end_date",sa.Date(),nullable=False), sa.Column("status",sa.String(32),nullable=False), sa.Column("action_type",sa.String(32)), sa.Column("event_count",sa.Integer()), sa.Column("evidence",sa.JSON()), sa.Column("validation_rule",sa.String(64)), sa.Column("summary",sa.JSON()), sa.Column("computed_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
def downgrade():
    op.drop_table("corporate_action_coverage_facts"); op.drop_constraint("uq_corp_fact_version", "corporate_action_facts", type_="unique"); op.drop_index("ix_corp_facts_instrument_date",table_name="corporate_action_facts"); op.drop_table("corporate_action_facts"); op.drop_index("ix_corp_source_code_ann",table_name="corporate_action_source_facts"); op.drop_table("corporate_action_source_facts")
