const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022},fileName:filename}).outputText,filename);
const {comparisonReason,selectedMetric,metricDifference,canonical,comparisonUrl,parseSelection}=require('../src/pages/backtests/comparisonData.ts');
const a='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',b='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const run={backtest_config:{spec:{start_date:'2026-01-01',end_date:'2026-02-01',currency:'CNY',timezone:'Asia/Shanghai',frequency:'1d'}}};
const metric={value:'.1',formula_version:'1',analyzer_key:'performance',analyzer_version:1,unit:'ratio',sample_count:20,analyzer_metadata:{return_basis:'equity'}};
test('comparison requires matching periods and actual calculation evidence',()=>{assert.equal(comparisonReason(run,run,metric,metric),'');assert.match(comparisonReason(run,{backtest_config:{...run.backtest_config.spec,end_date:'2026-03-01'}},metric,metric),/区间不同/);for(const change of [{formula_version:'2'},{analyzer_key:'other'},{sample_count:21},{analyzer_metadata:{return_basis:'cash'}}])assert.match(comparisonReason(run,run,metric,{...metric,...change}),/口径或样本/);assert.match(comparisonReason(run,run,metric,{...metric,unit:null}),/不完整/);assert.match(comparisonReason(run,run,metric,{...metric,value:null}),/不可计算/);});
test('ambiguous metric versions cannot be selected or ranked',()=>{const row={...metric,run_id:a,metric_key:'total_return'};assert.equal(selectedMetric([row],a,'total_return'),row);assert.equal(selectedMetric([row,{...row,formula_version:'2'}],a,'total_return'),undefined);});
test('canonical conventions ignore object insertion order but preserve member order',()=>{assert.equal(canonical({b:2,a:{y:1,x:0}}),canonical({a:{x:0,y:1},b:2}));assert.notEqual(canonical([a,b]),canonical([b,a]));assert.equal(metricDifference('.2','.1',true),'+10.00 个百分点');assert.equal(metricDifference(null,0,true),'—');});
test('selection links preserve order and baseline and reject invalid membership',()=>{const parse=url=>parseSelection(new URL(url,'http://local').searchParams);assert.deepEqual(parse(comparisonUrl([a,b],b)),{ids:[a,b],baseline:b,error:''});for(const q of ['runs='+a+','+a,'runs=bad','runs='+a+'&baseline='+b])assert.ok(parseSelection(new URLSearchParams(q)).error);assert.equal(new URL(comparisonUrl([], '', a),'http://local').searchParams.has('runs'),true);});
test('saved comparison requests retain optimistic versions, order and explicit baseline',async()=>{const api=require('../src/api/backtestComparisons.ts');const old=global.fetch,seen=[];global.fetch=async(url,init)=>{seen.push([url,init]);return{ok:true,status:init.method==='DELETE'?204:200,json:async()=>({})}};try{await api.fetchComparison([a,b],b);await api.saveComparison({id:a,name:'对比',run_ids:[a,b],baseline_run_id:b});await api.updateComparison(a,{version:3,name:'新名'});await api.deleteComparison(a,4);assert.deepEqual(JSON.parse(seen[0][1].body),{run_ids:[a,b],baseline_run_id:b});assert.equal(JSON.parse(seen[1][1].body).id,a);assert.equal(JSON.parse(seen[2][1].body).version,3);assert.match(seen[3][0],/version=4$/);assert.equal(seen[3][1].method,'DELETE');}finally{global.fetch=old}});

test('missing annualization, sample and risk-free conventions cannot establish comparability',()=>{for(const [change,reason] of [[{sample_count:null},/样本口径/],[{metric_key:'volatility'},/年化口径/],[{metric_key:'sharpe',annualization_factor:'252'},/无风险利率/]])assert.match(comparisonReason(run,run,{...metric,...change},{...metric,...change}),reason);});
