/* Isolated comparison workflow. No fixture request reaches the real backend. */
const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.connectOverCDP(process.env.CDP_URL||'http://127.0.0.1:9421');
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(()=>sessionStorage.setItem('quant-foundry.api-token','isolated-comparison-fixture'));
 const page=await context.newPage(),errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
 const ids=Array.from({length:21},(_,i)=>`aaaaaaaa-aaaa-4aaa-8aaa-${String(i+1).padStart(12,'0')}`);let saved=null,failSave=false,failPatch=false,deletes=0,saveIds=[],workspaceQueries=[];
 const config={start_date:'2026-01-05',end_date:'2026-02-02',currency:'CNY',timezone:'Asia/Shanghai',frequency:'1d'};
 const run=id=>({run_id:id,status:'succeeded',strategy_id:'strategy',strategy_revision_id:'revision',strategy_name:`ETF轮动${ids.indexOf(id)+1}`,revision_number:8,revision_alias:'优化止损逻辑',backtest_config:{spec:config},parameters:{lookback:40+ids.indexOf(id)},data_evidence:{session_evidence_available:true}});
 const comparison=(selected,baseline)=>({baseline_run_id:baseline,run_summaries:selected.map(run),equity_curve_series:selected.map((id,i)=>({run_id:id,points:[0,1,2,3].map((n)=>({as_of:`2026-01-0${n+5}T07:00:00Z`,cumulative_return:n===1?null:String(.05*(i+1)+n*.01),drawdown:n===1?null:'-.02',valuation_status:n===1?'blocked':'complete'}))})),metric_matrix:selected.flatMap((id,i)=>['total_return','annualized_return','max_drawdown','sharpe','volatility','turnover','cumulative_fees'].map(metric_key=>({run_id:id,metric_key,value:String(.1+i*.05),unit:'ratio',formula_version:'1',analyzer_key:'performance',analyzer_version:1,sample_count:20,annualization_factor:'252',risk_free_rate_note:'zero',analyzer_metadata:{}}))),configuration_diff:selected.filter(id=>id!==baseline).map(id=>({run_id:id,baseline_run_id:baseline,fields:{'parameters.lookback':{baseline:run(baseline).parameters.lookback,current:run(id).parameters.lookback,baseline_present:true,current_present:true}}}))});
 await context.route(url=>url.pathname.startsWith('/api/'),async route=>{const req=route.request(),u=new URL(req.url()),path=u.pathname;let body={},status=200;
  if(path.endsWith('/backtests/compare')){const p=req.postDataJSON();body=comparison(p.run_ids,p.baseline_run_id);if(p.run_ids.includes(ids[2]))body.run_summaries.find(r=>r.run_id===ids[2]).backtest_config={spec:{...config,start_date:'2026-01-01'}};}
  else if(path==='/api/admin/backtest-comparisons'){
    if(req.method()==='POST'){const p=req.postDataJSON();saveIds.push(p.id);if(failSave){status=503;body={detail:'暂时不可用，请重试'};failSave=false}else{saved={...p,version:1,created_at:'2026-09-14',updated_at:'2026-09-14'};status=201;body=saved}}
    else body={items:saved?[saved]:[],total:saved?1:0,offset:0,limit:20,has_more:false};
  }else if(path.startsWith('/api/admin/backtest-comparisons/')){
    if(req.method()==='PATCH'){const p=req.postDataJSON();assert.equal(p.version,saved.version);if(failPatch){failPatch=false;status=409;body={detail:'对比已被修改，请重新读取'}}else{saved={...saved,...p,version:saved.version+1};body=saved}}
    else if(req.method()==='DELETE'){assert.equal(Number(u.searchParams.get('version')),saved.version);deletes++;saved=null;status=204}else body=saved;
  }else if(path.endsWith('/workspace')){workspaceQueries.push(u.search);assert.equal(u.searchParams.get('status')||'succeeded','succeeded');const offset=Number(u.searchParams.get('offset')||0);const items=u.searchParams.get('search')?ids.filter(id=>run(id).strategy_name.includes(u.searchParams.get('search'))||id.includes(u.searchParams.get('search'))):ids;body={items:items.slice(offset,offset+20).map(run),total:items.length,offset,limit:20,has_more:offset+20<items.length}}
  else if(path.endsWith('/revisions'))body=[{id:'revision',revision_number:8,alias:'优化止损逻辑'}];
  else if(path.includes('/results/'))body={items:[]};else if(path.includes('/backtest-runs/'))body=run(path.split('/').at(-1));else if(path.includes('auth'))status=204;else if(path.includes('version'))body={version:'0.2.0'};
  await route.fulfill({status,contentType:'application/json',body:status===204?'':JSON.stringify(body)});
 });
 const choose=async locator=>{await locator.click();await page.waitForFunction(label=>document.querySelector(`input[aria-label="${label}"]`)?.checked,await locator.getAttribute('aria-label'));};
 const base=process.env.FRONTEND_URL||'http://127.0.0.1:5174';
 try{
  await page.goto(base+'/admin/backtest-compare');await page.getByText('请选择至少2个已完成运行开始对比。').waitFor();
  await page.getByRole('button',{name:'添加运行',exact:true}).first().click();let dialog=page.getByRole('dialog');await dialog.getByText('优化止损逻辑',{exact:true}).first().waitFor();await choose(dialog.getByRole('checkbox').first());await choose(dialog.getByRole('checkbox').nth(1));await dialog.getByRole('button',{name:'下一页',exact:true}).click();await dialog.getByText('ETF轮动21 · v8',{exact:true}).waitFor();await dialog.getByRole('button',{name:'上一页',exact:true}).click();await dialog.getByRole('checkbox').first().waitFor();await dialog.getByRole('button',{name:'完成选择'}).click();
  await page.getByRole('heading',{name:'关键指标',exact:true}).waitFor();await page.getByText('相对基准 +5.00 个百分点').first().waitFor();const color=await page.locator('.qcmp-run-top>span').nth(1).evaluate(e=>e.style.color);
  await page.locator('.qcmp-run').nth(1).getByRole('button',{name:'设为基准'}).click();await page.getByText('相对基准 -5.00 个百分点').first().waitFor();assert.equal(await page.locator('.qcmp-run-top>span').nth(1).evaluate(e=>e.style.color),color);assert.ok(new URL(page.url()).searchParams.get('baseline')===ids[1]);
  const paths=await page.locator('.qcmp-plot').first().locator('svg path').evaluateAll(es=>es.map(e=>e.getAttribute('d')));assert.equal((paths[0].match(/M/g)||[]).length,2);await page.screenshot({path:'/tmp/qcmp-desktop.png'});await page.getByRole('heading',{name:'累计收益对比',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/qcmp-charts.png'});await page.getByRole('heading',{name:'风险 / 收益分布',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/qcmp-risk.png'});
  failSave=true;await page.getByRole('button',{name:'保存对比',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('textbox',{name:'对比名称'}).fill('止损方案对比');await dialog.getByRole('button',{name:'保存',exact:true}).click();await dialog.getByRole('alert').waitFor();await dialog.getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('heading',{name:'止损方案对比',exact:true}).waitFor();assert.equal(saveIds[0],saveIds[1]);assert.equal(saved.baseline_run_id,ids[1]);
  await page.reload();await page.getByRole('heading',{name:'关键指标'}).waitFor();assert.equal(await page.locator('.qcmp-run').count(),2);
  await page.getByRole('button',{name:'已保存的对比',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'重命名'}).click();await page.getByRole('textbox',{name:'对比名称'}).fill('新版对比');failPatch=true;await page.getByRole('dialog').getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('alert').filter({hasText:'重新读取'}).waitFor();await page.getByRole('dialog').getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('dialog').getByText('新版对比',{exact:true}).waitFor();await page.getByRole('dialog').getByRole('button',{name:'打开',exact:true}).click();await page.getByRole('heading',{name:'新版对比'}).waitFor();
  await page.locator('.qcmp-run').first().getByRole('button',{name:'查看结果'}).click();await page.getByRole('button',{name:'返回对比',exact:true}).click();await page.getByRole('heading',{name:'新版对比'}).waitFor();
  await page.getByRole('button',{name:'添加运行',exact:true}).first().click();dialog=page.getByRole('dialog');await dialog.getByRole('textbox',{name:'搜索已完成运行'}).fill('ETF轮动3');await dialog.getByText('ETF轮动3 · v8',{exact:true}).waitFor();await page.waitForFunction(()=>document.querySelectorAll('dialog input[type=checkbox]').length===1);await choose(dialog.getByRole('checkbox'));await dialog.getByRole('button',{name:'完成选择'}).click();await page.getByText('回测区间不同',{exact:true}).first().waitFor();assert.equal(await page.locator('.qcmp-best').count(),0);assert.match(await page.locator('.qcmp-plot').first().innerText(),/原始|ETF/);
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);await page.screenshot({path:'/tmp/qcmp-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.getByRole('heading',{name:'累计收益对比',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/qcmp-charts-mobile.png'});
  await page.getByRole('button',{name:'添加运行',exact:true}).first().click();await page.getByRole('dialog').getByRole('checkbox').first().waitFor();await page.waitForFunction(()=>document.querySelector('dialog input[type=checkbox]:not(:disabled)'));for(let i=3;i<10;i++)await choose(page.getByRole('dialog').getByRole('checkbox').nth(i));assert.equal(await page.getByRole('dialog').getByRole('checkbox').nth(10).isDisabled(),true);await page.screenshot({path:'/tmp/qcmp-drawer-mobile.png'});await page.getByRole('dialog').getByRole('button',{name:'完成选择'}).click();await page.getByRole('heading',{name:'关键指标'}).waitFor();assert.equal(await page.locator('.qcmp-run').count(),10);
  await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'已保存的对比',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'删除',exact:true}).click();await page.getByRole('button',{name:'取消',exact:true}).click();assert.equal(deletes,0);await page.getByRole('dialog').getByRole('button',{name:'删除',exact:true}).click();await page.getByRole('button',{name:'确认删除',exact:true}).click();await page.getByText('尚无保存的对比。').waitFor();assert.equal(deletes,1);await page.getByRole('button',{name:'关闭已保存的对比'}).click();assert.equal(new URL(page.url()).searchParams.has('saved'),false);
  assert.ok(workspaceQueries.some(q=>q.includes('offset=20')));assert.deepEqual(errors,[]);console.log('PASS: selection, pagination/search, 10-run limit, baseline/color, curve gaps, metric comparability, save retry, rename/conflict, reopen, delete guard, result return, mobile');
 }finally{await context.close();await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
