import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { RefreshCw } from 'lucide-react';
import { foundationApi, FoundationApiError } from '../api/foundation';
import { useAuth } from '../auth/AuthContext';
import { Select } from '../components/controls/Select';
import { EvidencePanel, References } from './DataAssetsPage';
import { FoundationBatchLedger, FoundationIntakeLedger } from './FoundationBatchLedger';
import './DataAssets.css';

export interface RecordDataset {
  kind:'typed_records'; business_date_field:string|null; dataset:string; name:string; version:string; as_of:string;
  official_count:number; candidate_count:number; business_as_of:string|null;
  fields:{key:string;required:boolean}[]; limitations:string[];
  series:{series:string;source:string;release_id:string|null;official_count:number;published_at:string|null;range:{from:string|null;to:string|null}}[];
}
interface SubjectPage {items:{id:string;source_key:string;source:string}[];next_after:string|null;release_id:string}
interface Result {state:string;request_satisfied:boolean;resolution_token?:string;expires_at?:number;checked_at:string;items:Record<string,unknown>[];requirements:{id:string;result:string;message?:string}[];excluded:{target_key:string;reason:string}[];next_cursor?:string|null;has_more:boolean}
const ROOT='/admin/data-assets';
const labels:Record<string,string>={source_code:'来源代码',asset_type:'资产类型',name:'名称',exchange:'交易所',currency:'币种',listing_date:'上市日期',end_date:'终止日期',company_id:'公司来源标识',company_type:'公司类型',established_date:'成立日期',fund_count:'基金数量',manager_id:'经理来源标识',company_name:'公司名称',degree:'学历',resume:'履历',manager_name:'经理名称',management_name:'管理机构',exchange_scope:'日期范围主体',calendar_date:'日期',is_open:'是否开市',scope_basis:'范围依据',trade_date:'交易日期',factor:'来源复权因子',factor_basis:'因子口径',anchor_date:'复权锚点日期',collection_key:'集合来源标识',collection_kind:'集合类型',membership_basis:'成员口径',members:'成员集合'};
const states:Record<string,string>={available:'满足请求',partial:'部分满足',unavailable:'不满足请求',unknown:'证据不足',CURRENT_ISSUE:'当前问题限制',FIELD_UNAVAILABLE:'字段缺项或语义未验证',SUBJECT_UNAVAILABLE:'主体在当前范围没有正式对象',RECORD_MISSING:'缺少指定正式对象',blocked:'已阻断',withdrawn:'已撤回',gap:'缺口'};
const time=(value:string)=>new Date(value).toLocaleString('zh-CN',{hour12:false});
const sourceName=(source:string)=>source==='tushare'?'Tushare':'同花顺';
const valueText=(value:unknown)=>value===null||value===undefined?'缺项':value===true?'是':value===false?'否':value==='provider_reported_snapshot'?'供应商报告快照':value==='category'?'指数分类':value==='index'?'指数':value==='provider_reported_dates'?'供应商报告日期集合':value==='declared_exchange'?'明确交易所范围':value==='tushare_fund_adj'?'Tushare 基金复权因子':String(value);

/** Keep discovery separate from value reads: selecting a source-local identity
 * never bypasses the signed capability check, current restrictions, or lineage. */
export function RecordAssetsPage({datasetId}:{datasetId:string}) {
  const [params,setParams]=useSearchParams(),navigate=useNavigate(),{logout}=useAuth();
  const [dataset,setDataset]=useState<RecordDataset|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0);
  const [subjects,setSubjects]=useState<SubjectPage|null>(null),[subjectBusy,setSubjectBusy]=useState(false),[subjectAfter,setSubjectAfter]=useState<(string|null)[]>([null]),[subjectPage,setSubjectPage]=useState(0);
  const [result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[readDone,setReadDone]=useState(false),[page,setPage]=useState(0),[cursors,setCursors]=useState<(string|null)[]>([null]);
  const [panel,setPanel]=useState<{title:string;content:ReactNode}|null>(null),[clock,setClock]=useState(Date.now());
  const active=useRef<AbortController|null>(null),aux=useRef<AbortController|null>(null);
  const failure=useCallback((e:unknown)=>{if(e instanceof FoundationApiError&&[401,403].includes(e.status)){active.current?.abort();aux.current?.abort();setDataset(null);setSubjects(null);setResult(null);setPanel(null);logout();navigate('/login',{replace:true});}return e instanceof Error?e.message:'读取失败，请重试。';},[logout,navigate]);
  const series=dataset?.series.find(s=>s.series===params.get('series'))||dataset?.series.find(s=>s.release_id)||dataset?.series[0];
  const release=params.get('release')||series?.release_id||'';
  const selected=(params.get('subjects')||'').split(',').filter(Boolean);
  const fields=(params.has('fields')?params.get('fields')||'':dataset?.fields.filter(f=>f.required).map(f=>f.key).join(',')||'').split(',').filter(Boolean);
  const from=params.get('from')||series?.range.from||'',to=params.get('to')||series?.range.to||'';
  const view=params.get('view')||'data',search=params.get('subject_search')||'',partial=params.get('partial')==='true';
  const size=[20,50,100].includes(Number(params.get('size')))?Number(params.get('size')):50;
  const identity=JSON.stringify([datasetId,series?.series,release,search]);
  const intent=JSON.stringify([identity,selected,fields,from,to,partial,size]);
  const expired=!!result?.expires_at&&clock>=result.expires_at*1000;
  function update(key:string,value:string){const p=new URLSearchParams(params);p.set(key,value);if(key==='series'){p.delete('release');p.delete('subjects');p.delete('from');p.delete('to');}setParams(p);}
  useEffect(()=>{const c=new AbortController();setLoading(true);foundationApi<RecordDataset>(`/datasets/${datasetId}`,c.signal).then(d=>{if(!c.signal.aborted){setDataset(d);setError('');}}).catch(e=>{if(!c.signal.aborted)setError(failure(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[datasetId,revision,failure]);
  // Pin the discovered head in navigation. Background refreshes may reveal a
  // newer head but cannot silently change a user's checked historical release.
  useEffect(()=>{if(!series?.release_id||params.has('release'))return;const p=new URLSearchParams(params);p.set('release',series.release_id);p.set('series',series.series);setParams(p,{replace:true});},[series,params,setParams]);
  useEffect(()=>{setSubjectAfter([null]);setSubjectPage(0);setSubjects(null);},[identity]);
  useEffect(()=>{if(!release||!series)return;const c=new AbortController();setSubjectBusy(true);const q=new URLSearchParams({series:series.series,release_id:release,search,limit:'50'});if(subjectAfter[subjectPage])q.set('after',subjectAfter[subjectPage]!);foundationApi<SubjectPage>(`/datasets/${datasetId}/subjects?${q}`,c.signal).then(r=>{if(!c.signal.aborted)setSubjects(r);}).catch(e=>{if(!c.signal.aborted)setError(failure(e));}).finally(()=>{if(!c.signal.aborted)setSubjectBusy(false);});return()=>c.abort();},[identity,subjectPage,subjectAfter,revision,failure]);
  useEffect(()=>{active.current?.abort();aux.current?.abort();setResult(null);setPanel(null);setBusy(false);setReadDone(false);setPage(0);setCursors([null]);},[intent]);
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>{clearInterval(timer);active.current?.abort();aux.current?.abort();};},[]);
  async function read(check:boolean,target=0){active.current?.abort();const c=new AbortController();active.current=c;setBusy(true);setError('');try{const request=check?{dataset_id:datasetId,semantic_series_id:series?.series,release,subjects:selected,fields,allow_partial:partial,page_size:size,...(dataset?.business_date_field?{business_range:{from,to}}:{})}:{resolution_token:result?.resolution_token,cursor:cursors[target],page_size:size};const r=await foundationApi<Result>(check?'/capability-checks':'/queries',c.signal,request);if(c.signal.aborted)return;setResult(r);setReadDone(!check);setPage(target);if(check)setCursors([null]);else if(r.next_cursor)setCursors(old=>[...old.slice(0,target+1),r.next_cursor!]);}catch(e){if(!c.signal.aborted){if(e instanceof FoundationApiError&&[409,410].includes(e.status)){setResult(null);setPanel(null);setCursors([null]);setPage(0);}setError(failure(e));}}finally{if(!c.signal.aborted)setBusy(false);}}
  async function lineage(id:string){aux.current?.abort();const c=new AbortController();aux.current=c;try{const r=await foundationApi<Record<string,unknown>>(`/revisions/${id}/lineage`,c.signal);if(!c.signal.aborted)setPanel({title:'正式记录血缘',content:<References values={r}/>});}catch(e){if(!c.signal.aborted)setError(failure(e));}}
  return <section className="qf-assets qf-record-assets" aria-busy={loading||busy}><header className="qf-assets-heading"><div><Link to={`${ROOT}?search=${encodeURIComponent(params.get('search')||'')}&status=${params.get('status')||'all'}`}>数据资产</Link><h1>{dataset?.name||'领域数据'}</h1><p>查看来源主体的正式观察记录、契约与处理依据。</p></div><button className="qfo-secondary-btn" disabled={loading} onClick={()=>setRevision(r=>r+1)}><RefreshCw size={16}/>刷新</button></header>
    {error&&<p role="alert" className="qf-assets-error">{error}{dataset?' 当前保留上次成功读取的内容。':''}</p>}{!dataset&&!error&&<p role="status">正在读取领域资产…</p>}
    <nav className="qf-assets-tabs" aria-label="数据集视图">{[['data','概况与数据'],['fields','字段与口径'],['versions','来源与版本'],['process','处理过程']].map(([key,name])=><Link key={key} aria-current={view===key?'page':undefined} to={`?${new URLSearchParams({...Object.fromEntries(params),view:key})}`}>{name}</Link>)}</nav>
    {dataset&&<><div className="qf-assets-metrics"><div><span>候选记录</span><strong>{dataset.candidate_count}</strong><small>条</small></div><div><span>当前正式对象</span><strong>{dataset.official_count}</strong><small>条</small></div></div><div className="qf-assets-note"><p>主体仅在各来源内识别，不能视为已统一的证券身份。当前支持本地观察版本，历史公开时点未经验证。</p><p>正式数量仅表示已发布对象，不证明来源全量覆盖。缺少依据的可选字段保持缺项。</p>{datasetId==='market.calendar'&&<p>供应商报告的日期集合不能证明交易所开闭市状态；是否开市字段未经验证时不可读。</p>}</div>
    <div className="qf-assets-form"><label>来源口径<Select value={series?.series||''} onChange={e=>update('series',e.target.value)}>{dataset.series.map(s=><option key={s.series} value={s.series}>{sourceName(s.source)} · 本地观察版本</option>)}</Select></label></div><p>所选正式版本：<code>{release||'暂无正式发布'}</code></p>{release!==series?.release_id&&series?.release_id&&<button className="qfo-secondary-btn" onClick={()=>update('release',series.release_id!)}>切换到当前正式版本</button>}
    {view==='data'&&<section className="qf-assets-sheet"><h2>检查与正式读取</h2>{!release?<p>本口径尚未正式发布，来源或候选记录不能直接用于正式读取。</p>:<><label>搜索主体来源标识<input value={search} onChange={e=>update('subject_search',e.target.value)}/></label><p>已选择 {selected.length} 个主体，最多100个。</p>{subjectBusy&&<p role="status">正在读取主体目录…</p>}<fieldset><legend>来源主体</legend><div className="qf-assets-checks">{subjects?.items.map(s=><label key={s.id}><input type="checkbox" checked={selected.includes(s.id)} disabled={!selected.includes(s.id)&&selected.length>=100} onChange={e=>update('subjects',(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id)).join(','))}/>{s.source_key}</label>)}</div>{subjects&&!subjects.items.length&&<p>当前正式版本没有匹配的主体，请调整搜索条件。</p>}</fieldset><div className="qf-assets-controls"><button className="qfo-secondary-btn" disabled={subjectBusy||subjectPage===0} onClick={()=>setSubjectPage(p=>p-1)}>上一页主体</button><span>第 {subjectPage+1} 页主体</span><button className="qfo-secondary-btn" disabled={subjectBusy||!subjects?.next_after} onClick={()=>{setSubjectAfter(old=>[...old.slice(0,subjectPage+1),subjects!.next_after]);setSubjectPage(p=>p+1);}}>下一页主体</button><button className="qfo-secondary-btn" disabled={!selected.length} onClick={()=>update('subjects','')}>清空选择</button></div>
    {dataset.business_date_field&&<div className="qf-assets-form"><label>日期从<input type="date" value={from} onChange={e=>update('from',e.target.value)}/></label><label>日期至<input type="date" value={to} onChange={e=>update('to',e.target.value)}/></label></div>}
    <fieldset><legend>正式字段</legend><div className="qf-assets-checks">{dataset.fields.map(f=><label key={f.key}><input type="checkbox" checked={fields.includes(f.key)} onChange={e=>update('fields',(e.target.checked?[...fields,f.key]:fields.filter(k=>k!==f.key)).join(','))}/>{labels[f.key]||f.key}</label>)}</div></fieldset><label><input type="checkbox" checked={partial} onChange={e=>update('partial',String(e.target.checked))}/>允许读取已证明的子集</label><p>每次请求最多1000个正式对象；超过时请缩小主体或日期范围。</p><div className="qf-assets-controls"><button className="qfo-primary-btn" disabled={busy||!selected.length||!fields.length||(!!dataset.business_date_field&&(!from||!to||from>to))} onClick={()=>read(true)}>检查是否满足</button><button className="qfo-secondary-btn" disabled={busy||!result?.resolution_token||expired} onClick={()=>read(false)}>读取正式数据</button></div></>}
    {expired&&<p role="alert">检查已过期，请重新检查所选版本。</p>}{result&&<><h3>{states[result.state]||'证据不足'}</h3><p>{result.request_satisfied?'原请求已满足。':'原请求未满足；允许部分读取不会改变此结论。'} 检查于 {time(result.checked_at)}</p>{result.requirements.map(r=><p key={r.id}>{r.message||'所选范围缺少正式发布。'}（{r.result==='pass'?'通过':r.result==='unknown'?'证据不足':'未满足'}）</p>)}{result.items.length?<div className="qf-assets-scroll"><table><thead><tr><th>主体来源标识</th>{fields.map(f=><th key={f}>{labels[f]||f}</th>)}<th>依据</th></tr></thead><tbody>{result.items.map(row=><tr key={String(row.target_key)}><td>{String(row.source_key)}</td>{fields.map(f=><td key={f}>{f==='members'&&Array.isArray(row[f])?<button className="qfo-secondary-btn" onClick={()=>setPanel({title:`${String(row.source_key)} · 成员集合`,content:<IndexMembers members={row[f] as IndexMember[]}/>})}>查看成员（{row[f].length}）</button>:valueText(row[f])}</td>)}<td><button className="qfo-secondary-btn" onClick={()=>lineage(String(row.official_id))}>查看血缘</button></td></tr>)}</tbody></table></div>:<p>{readDone?'没有可读取的正式结果，请查看限制。':'检查完成，点击“读取正式数据”查看结果。'}</p>}<div className="qf-assets-controls"><button className="qfo-secondary-btn" disabled={busy||page===0||expired} onClick={()=>read(false,page-1)}>上一页</button><span>第 {page+1} 页</span><button className="qfo-secondary-btn" disabled={busy||!result.next_cursor||expired} onClick={()=>read(false,page+1)}>下一页</button><label>每页<Select value={String(size)} onChange={e=>update('size',e.target.value)}>{[20,50,100].map(n=><option key={n} value={String(n)}>{n} 条</option>)}</Select></label></div>{!!result.excluded.length&&<details open><summary>缺口与限制（{result.excluded.length} 项）</summary>{result.excluded.map(e=><p key={e.target_key}><code>{e.target_key}</code> · {states[e.reason]||'范围受限'}</p>)}</details>}</>}</section>}
    {view==='fields'&&<section className="qf-assets-sheet"><h2>契约 {dataset.version} · 来源观察记录</h2><div className="qf-assets-scroll"><table><thead><tr><th>字段</th><th>要求</th></tr></thead><tbody>{dataset.fields.map(f=><tr key={f.key}><td>{labels[f.key]||f.key}</td><td>{f.required?'核心必需':'可选；缺项时不满足该字段请求'}</td></tr>)}</tbody></table></div>{datasetId.startsWith('index.')&&<p>每个正式对象保存该来源主体的完整报告集合。后续快照整组替换，空集合表示来源明确报告零个成员；成员退出只改变新版本，旧发布仍可读取。成员代码属于同花顺命名空间，名称和简称保留来源文本；缺项显示为缺项，不推断成员生效日期、权重或历史公开时点。</p>}{datasetId==='market.adjustment_factor'&&<p>复权因子按来源十进制值保存，精度最多12位小数。锚点未经验证，不直接推导前复权或后复权价格。依据：<a href="https://tushare.pro/document/2?doc_id=199" target="_blank" rel="noreferrer">Tushare 基金复权因子说明</a>。</p>}<p>标识和文本按来源观察含义保存；日期为公历日期；基金数量为非负整数；开闭市状态为布尔值。资料记录没有业务日期，不能以日期过滤冒充历史时点读取。</p></section>}
    {view==='versions'&&<FoundationIntakeLedger datasetId={datasetId} refresh={revision} onError={failure}/>}{['versions','process'].includes(view)&&<FoundationBatchLedger datasetId={datasetId} refresh={revision} onError={failure}/>}<p className="qf-assets-asof">资产摘要读取于 {time(dataset.as_of)}。来源、候选与正式计数分别统计。</p></>}
    {panel&&<EvidencePanel title={panel.title} onClose={()=>{aux.current?.abort();setPanel(null);}}>{panel.content}</EvidencePanel>}
  </section>;
}

interface IndexMember {source_code:string;name:string|null;ticker:string|null}

/** Page the members already authorized by the fixed release read. Opening this
 * panel neither rereads a moving source nor silently truncates the snapshot. */
function IndexMembers({members}:{members:IndexMember[]}) {
  const [page,setPage]=useState(0),[size,setSize]=useState(50),[search,setSearch]=useState('');
  const filtered=members.filter(m=>[m.source_code,m.name,m.ticker].some(value=>value?.toLocaleLowerCase().includes(search.toLocaleLowerCase())));
  return <><p>来源报告共 {members.length} 个成员，匹配 {filtered.length} 个。成员有效日期与权重未经验证。</p>
    <label>搜索成员<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label>
    {filtered.length?<div className="qf-assets-scroll"><table><thead><tr><th>来源代码</th><th>名称</th><th>来源简称代码</th></tr></thead><tbody>{filtered.slice(page*size,(page+1)*size).map(m=><tr key={m.source_code}><td>{m.source_code}</td><td>{valueText(m.name)}</td><td>{valueText(m.ticker)}</td></tr>)}</tbody></table></div>:<p>{members.length?'没有匹配的成员，请调整搜索条件。':'该正式快照明确包含零个成员。'}</p>}
    <div className="qf-assets-controls"><button className="qfo-secondary-btn" disabled={page===0} onClick={()=>setPage(p=>p-1)}>上一页成员</button><span>第 {page+1} 页成员</span><button className="qfo-secondary-btn" disabled={(page+1)*size>=filtered.length} onClick={()=>setPage(p=>p+1)}>下一页成员</button><label>每页成员<Select value={String(size)} onChange={e=>{setSize(Number(e.target.value));setPage(0);}}>{[20,50,100].map(n=><option key={n} value={String(n)}>{n} 条</option>)}</Select></label></div>
  </>;
}
