# Exact reviewed legacy ownership; live catalog classification is still required.
LEGACY_TABLES = (
    'foundation_artifacts',
    'foundation_assessments',
    'foundation_backfill_completions',
    'foundation_backfill_probes',
    'foundation_backfill_receipts',
    'foundation_backfill_resume_watches',
    'foundation_bar_candidates',
    'foundation_bar_official_revisions',
    'foundation_baseline_blocks',
    'foundation_baselines',
    'foundation_batch_controls',
    'foundation_batch_dispositions',
    'foundation_batch_inputs',
    'foundation_batch_work',
    'foundation_batches',
    'foundation_block_members',
    'foundation_candidate_entries',
    'foundation_candidate_input_entries',
    'foundation_candidate_input_sets',
    'foundation_candidate_manifests',
    'foundation_candidates',
    'foundation_decisions',
    'foundation_definitions',
    'foundation_dependency_entries',
    'foundation_dependency_manifests',
    'foundation_execution_archives',
    'foundation_execution_manifests',
    'foundation_heads',
    'foundation_intake_campaign_scans',
    'foundation_intake_campaigns',
    'foundation_intake_controls',
    'foundation_intake_items',
    'foundation_intake_pointers',
    'foundation_intake_scan_entries',
    'foundation_intake_scan_failures',
    'foundation_intake_scan_seals',
    'foundation_intake_scan_targets',
    'foundation_intake_scans',
    'foundation_intake_scopes',
    'foundation_issue_revisions',
    'foundation_issue_scopes',
    'foundation_maintenance_plans',
    'foundation_maintenance_targets',
    'foundation_observation_dependencies',
    'foundation_official_releases',
    'foundation_reconciliations',
    'foundation_record_block_members',
    'foundation_record_block_page_verifications',
    'foundation_record_block_verifications',
    'foundation_record_candidates',
    'foundation_record_issues',
    'foundation_record_official_revisions',
    'foundation_record_plan_verifications',
    'foundation_record_preparations',
    'foundation_record_prepared_pages',
    'foundation_record_subjects',
    'foundation_record_validation_roots',
    'foundation_release_block_refs',
    'foundation_release_blocks',
    'foundation_release_contributions',
    'foundation_report_block_members',
    'foundation_report_candidate_members',
    'foundation_report_candidates',
    'foundation_report_issue_targets',
    'foundation_report_official_members',
    'foundation_report_official_revisions',
    'foundation_runtime_archives',
    'foundation_source_bindings',
    'foundation_source_refs',
    'foundation_table_change_visits',
    'foundation_table_changes',
    'foundation_table_settlement_receipts',
    'foundation_table_settlement_visits',
    'foundation_update_visits',
    'foundation_work',
    'foundation_work_attempts',
    'foundation_work_coverage',
    'foundation_work_events',
    'foundation_work_source_pointers',
    'foundation_work_units',
)

LEGACY_FUNCTIONS = (
    'foundation_capture_table_change',
    'foundation_guard_backfill_completion',
    'foundation_guard_backfill_probe',
    'foundation_guard_backfill_receipt',
    'foundation_guard_binding',
    'foundation_guard_block_insert',
    'foundation_guard_block_page_proof',
    'foundation_guard_candidate_entry',
    'foundation_guard_frozen_observation',
    'foundation_guard_head',
    'foundation_guard_input_entry',
    'foundation_guard_member_insert',
    'foundation_guard_observation',
    'foundation_guard_prepared_page',
    'foundation_guard_record_plan_verification',
    'foundation_guard_record_preparation',
    'foundation_guard_record_verification',
    'foundation_guard_ref_insert',
    'foundation_guard_release',
    'foundation_guard_report_head',
    'foundation_guard_report_members',
    'foundation_guard_scan',
    'foundation_guard_scan_target',
    'foundation_guard_table_settlement_receipt',
    'foundation_guard_table_settlement_scope',
    'foundation_guard_validation_root',
    'foundation_guard_work',
    'foundation_immutable',
    'foundation_lock_table_change',
    'foundation_reject_table_change_mutation',
)

SHARED_TRIGGERS = {
    'tonghuashun_observations': ('foundation_observation_guard', 'foundation_frozen_observation_guard'),
    'trading_calendar_days': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'etf_codes': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'etf_code_mapping_audits': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'etf_daily_bars': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'etf_daily_bar_revision_audits': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'etf_adjustment_factors': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'corporate_action_source_facts': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'corporate_action_facts': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'corporate_action_coverage_facts': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'trading_status_source_facts': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'trading_status_facts': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'trading_status_coverage_facts': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
    'trading_status_fact_revision_audits': ('foundation_lock_change', 'foundation_capture_change', 'foundation_source_no_truncate'),
}

ORIGINAL_CONTAINERS = ('foundation_baselines', 'foundation_baseline_blocks', 'foundation_table_changes')
LEGACY_TASK_TYPES = ('foundation.formalize_local_updates', 'foundation.formalize_local_table_updates')
