import { useEffect, useId, useRef, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight } from "lucide-react";
import { Select } from "./Select";
import { useControlPopover } from "./Popover";
import { calendarDays, dateKey, shiftMonth, todayKey } from "./calendar";
export function DatePicker({value,onChange,label,disabled,maxDate}:{value:string;onChange:(value:string)=>void;label:string;disabled?:boolean;maxDate?:string}){
  const [open,setOpen]=useState(false),[month,setMonth]=useState((value||todayKey()).slice(0,7));const trigger=useRef<HTMLButtonElement>(null);const {root,style}=useControlPopover(open,()=>setOpen(false),310);const id=useId();
  useEffect(()=>{if(open)setMonth((maxDate && (value||todayKey()) > maxDate ? maxDate : value||todayKey()).slice(0,7));},[open]);
  // Enforce the limit for every selection path, including keyboard and Today.
  function choose(day:string){if(maxDate && day > maxDate)return;onChange(day);setOpen(false);trigger.current?.focus();}
  const days=calendarDays(month),year=Number(month.slice(0,4));
  return <span className="qfc-control" ref={root} onKeyDown={e=>{if(e.key==='Escape'&&open){e.preventDefault();e.stopPropagation();setOpen(false);trigger.current?.focus();}}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}>
    <button ref={trigger} className="qfc-trigger" type="button" aria-label={label} aria-haspopup="dialog" aria-expanded={open} disabled={disabled} onClick={()=>setOpen(o=>!o)}><span>{value?value.replaceAll('-',' / '):'选择日期'}</span><CalendarDays size={16} aria-hidden="true"/></button>
    {open&&<span className="qfc-popover qfc-calendar" style={style} role="dialog" aria-label={`${label}日历`}><span className="qfc-calendar-head"><button type="button" aria-label="上个月" onClick={()=>setMonth(shiftMonth(month,-1))}><ChevronLeft size={16}/></button><Select aria-label="年份" value={String(year)} onChange={e=>setMonth(maxDate && `${e.target.value}-${month.slice(5)}` > maxDate.slice(0,7) ? maxDate.slice(0,7) : `${e.target.value}-${month.slice(5)}`)}>{Array.from({length:(maxDate ? Number(maxDate.slice(0,4)) : Math.max(2100,year))-1900+1},(_,i)=><option key={i} value={String(1900+i)}>{1900+i}年</option>)}</Select><Select aria-label="月份" value={month.slice(5)} onChange={e=>setMonth(`${year}-${e.target.value}`)}>{Array.from({length:12},(_,i)=><option key={i} disabled={!!maxDate && `${year}-${String(i+1).padStart(2,'0')}` > maxDate.slice(0,7)} value={String(i+1).padStart(2,'0')}>{i+1}月</option>)}</Select><button type="button" aria-label="下个月" disabled={!!maxDate && shiftMonth(month,1) > maxDate.slice(0,7)} onClick={()=>setMonth(shiftMonth(month,1))}><ChevronRight size={16}/></button></span>
      <span className="qfc-week">{'日一二三四五六'.split('').map(day=><span key={day}>{day}</span>)}</span><span className="qfc-days" role="group" aria-label={`${year}年${Number(month.slice(5))}月`}>
        {days.map(day=><button key={day} id={`${id}-${day}`} type="button" aria-label={day} disabled={!!maxDate && day > maxDate} aria-pressed={day===value} aria-current={day===todayKey()?'date':undefined} className={`${day.slice(0,7)!==month?'is-outside':''} ${day===value?'is-selected':''}`} onClick={()=>choose(day)} onKeyDown={e=>{const offset=({ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7} as Record<string,number>)[e.key];if(offset){e.preventDefault();const date=new Date(`${day}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+offset);const next=dateKey(date);if(maxDate && next > maxDate)return;if(!days.includes(next))setMonth(next.slice(0,7));setTimeout(()=>document.getElementById(`${id}-${next}`)?.focus(),0);}}}>{Number(day.slice(8))}</button>)}
      </span><span className="qfc-calendar-foot"><button type="button" onClick={()=>choose('')}>清除</button><button type="button" disabled={!!maxDate && todayKey() > maxDate} onClick={()=>choose(todayKey())}>今天</button></span></span>}
  </span>;
}
