import { useEffect, useRef, useState } from "react";
import { Search, ChevronDown, Check } from "lucide-react";
import { listEtfs, type EtfCode } from "../../api/dataCollections";
import { useControlPopover } from "./Popover";
/** Resolve the persisted ETF identity while showing only its catalogue name/code.
 * A selection is not a claim of historical tradability; preflight remains required.
 */
export function InstrumentPicker({value,onChange,label="标的",disabled=false,exclude=[],compact=false}:{value:string;onChange:(id:string)=>void;label?:string;disabled?:boolean;exclude?:string[];compact?:boolean}){
  const [open,setOpen]=useState(false),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[items,setItems]=useState<EtfCode[]>([]),[selected,setSelected]=useState<EtfCode|null>(null),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const button=useRef<HTMLButtonElement>(null),input=useRef<HTMLInputElement>(null);const {root,style}=useControlPopover(open,()=>setOpen(false),420);
  useEffect(()=>{if(!value){setSelected(null);return;}if(selected?.instrument_id===value)return;const controller=new AbortController();setSelected(null);listEtfs({instrumentId:value,limit:1},controller.signal).then(page=>{if(!controller.signal.aborted)setSelected(page.items.find(row=>row.instrument_id===value)||null);}).catch(()=>{});return()=>controller.abort();},[value]);
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(search.trim());setOffset(0);},250);return()=>clearTimeout(timer);},[search]);
  useEffect(()=>{if(open){setSearch('');input.current?.focus();}},[open]);
  useEffect(()=>{if(!open)return;const controller=new AbortController();setLoading(true);setError('');listEtfs({keyword:query,limit:20,offset},controller.signal).then(page=>{if(!controller.signal.aborted){setItems(page.items);setTotal(page.total);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[open,query,offset]);
  function choose(item:EtfCode){if(!item.instrument_id)return;setSelected(item);onChange(item.instrument_id);setOpen(false);button.current?.focus();}
  return <span className="qfc-control" ref={root} onKeyDown={e=>{if(e.key==='Escape'&&open){e.preventDefault();e.stopPropagation();setOpen(false);button.current?.focus();}if(open&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const options=Array.from(root.current?.querySelectorAll<HTMLButtonElement>('[role=option]:not(:disabled)')||[]);const index=options.indexOf(document.activeElement as HTMLButtonElement);options[(index+(e.key==='ArrowDown'?1:-1)+options.length)%options.length]?.focus();}}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}>
    <button ref={button} type="button" className="qfc-trigger" role="combobox" aria-label={label} aria-expanded={open} aria-haspopup="listbox" disabled={disabled} onClick={()=>setOpen(o=>!o)}><span className={compact ? "qfc-selected-instrument" : undefined}>{value&&selected?.instrument_id===value ? compact ? <><span>{selected.csname||selected.cname||selected.ts_code}</span><small>{selected.ts_code}</small></> : `${selected.csname||selected.cname||selected.ts_code} · ${selected.ts_code}` : value?'标的信息待确认，请重新选择':'搜索标的名称或代码'}</span><ChevronDown size={16}/></button>
    {open&&<span className="qfc-popover" style={style}><span className="qfc-search"><Search size={16}/><input ref={input} aria-label={`搜索${label}`} placeholder="输入名称或代码，例如 沪深300、510300" value={search} maxLength={128} onChange={e=>setSearch(e.target.value)}/></span>
      <span role="listbox" aria-label={`${label}搜索结果`} className="qfc-options">{error?<span className="qfc-no-options" role="alert">{error}</span>:loading?<span className="qfc-no-options">正在搜索…</span>:items.length?items.map(item=><button type="button" role="option" aria-selected={item.instrument_id===value} disabled={!item.instrument_id||exclude.includes(item.instrument_id)&&item.instrument_id!==value} key={item.ts_code} onClick={()=>choose(item)}><span className="qfc-instrument-option"><span>{item.csname||item.cname||item.ts_code}</span><small>{item.ts_code} · {item.exchange}{!item.instrument_id?' · 标的映射尚未提供':exclude.includes(item.instrument_id)&&item.instrument_id!==value?' · 已选择':''}</small></span>{item.instrument_id===value&&<Check size={15}/>}</button>):<span className="qfc-no-options">没有匹配的标的</span>}</span>
      <span className="qfc-page-more"><span>共 {total} 个标的</span><button type="button" disabled={loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}>上一页</button><button type="button" disabled={loading||offset+20>=total} onClick={()=>setOffset(offset+20)}>下一页</button></span>
    </span>}
  </span>;
}
